version: '3.9'

services:
  product_backend:
    build: .
    # build:
    #   dockerfile: Dockerfile.local
    #   context: .
    #   target: dev
    container_name: product_backend
    ports:
      - 4001:4000
    volumes:
      - .:/app
    depends_on:
      - product_database
      # -products  
    networks:
      - product

  product_database:
    image: 'mariadb:10.1.24'
    container_name: product_database
    restart: always
    # ports:
    #   - 33037:3306 
    environment:
       MYSQL_DATABASE: product
       MYSQL_ROOT_PASSWORD: Johnanthom@7
    volumes:
      - .dbdata:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d
    networks:
      - product


networks:
  product:
